### PR TITLE
Fairy Wand Weapon

### PR DESCRIPTION
**Pull request by CatIcedTea**
Edit: Changed Fairy Wand weapon to work with the current generic Equipment Manager. Edited the values in the player's equipment manager prefab. Deleted old files not needed anymore.

Has FairyWand script which does nothing but has stored default values (can be removed if neccessary). Also has FairyWandProjectile script that extends the generic Projectile script but destroys itself after 5 seconds to stop it from infinitely spawning (can be changed later if pooling is added).

Does not currently have collision detection and damage checks as we are still figuring it out.

Weapons can be tested with the "Justin Upgrade" scene by pressing "p" and selecting the equipment.

### CODE REVIEW

**Review by MistOfJudgement — CHANGES_REQUESTED** [review]
The enemy template script was updated to have it's own health and damage functions. Does it make sense for enemies to have a separate component for health? 

If we should have a component for health, a small nitpick is that instead of checking health every update call, you can run the checks in increment or decrement health. If we shouldn't have a component for health, the projectile code should probably be updated.

I don't believe rotationPosition and nearestEnemy of FairyWandWeapon.cs should be private fields. They should be local variables of the update method.

**Review by MistOfJudgement — CHANGES_REQUESTED** [review]
I'm getting a namespace issue on Weapon due to there being two Weapon classes: one in Assets/Scripts/Weapons/Weapon.cs and one in Assets/Scripts/Equipment/Weapons/Weapon.cs. Other than that I think it looks good.

**Comment by CatIcedTea** [comment]
> I'm getting a namespace issue on Weapon due to there being two Weapon classes: one in Assets/Scripts/Weapons/Weapon.cs and one in Assets/Scripts/Equipment/Weapons/Weapon.cs. Other than that I think it looks good.

I think thats because the Weapon script in Assets/Scripts/Weapons/Weapon.cs is the old location. The one in Assets/Scripts/Equipment/Weapons/Weapon.cs is the new location due to reorganizing of the folders and files on the main branch. My branch currently shouldn't change or interfere with it I don't think.

**Review by MistOfJudgement — CHANGES_REQUESTED** [review]
Based on the comment in ProjectileWeapon, I think this FairyWand.cs shouldn't exist and these stats should be set in the EquipmentManager prefab on the player in the Inspector. ProjectileWeapon is a sealed class which means it can't be inherited from, which is also causing a compile issue.

**Comment by CatIcedTea** [comment]
> Based on the comment in ProjectileWeapon, I think this FairyWand.cs shouldn't exist and these stats should be set in the EquipmentManager prefab on the player in the Inspector. ProjectileWeapon is a sealed class which means it can't be inherited from, which is also causing a compile issue.

Should be deleted now.

**Review by MistOfJudgement — CHANGES_REQUESTED** [review]
Enemy collisions need to be finalized on the enemy side so ignoring that i think is kinda fine for now.
FairyWandProjectile prefab needs to be set in the equipment manager as well.

**Review by MistOfJudgement — APPROVED** [review]

**Pull request merged**
